osx_image: xcode10.1
before_script:
  - swift package --package-path HelloWorld  generate-xcodeproj
language: objective-c
xcode_project: HelloWorld/HelloWorld.xcodeproj # path to your xcodeproj folder
xcode_scheme: HelloWorld-Package
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone XS
